---
services:
  devcontainer:
    image: jarppe/clj-devcontainer:dev
    command: "sleep infinity"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/home/${USER}/.kube:ro
      - .:/home/${USER}/workspace
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
