#!/bin/bash

JAVA_VERSION=$1
if [[ -z "${JAVA_VERSION}" ]]; then
  JAVA_VERSION=23
fi

echo "Installing Java $JAVA_VERSION..."

curl -sSLf https://packages.adoptium.net/artifactory/api/gpg/key/public \
  | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/temurin.gpg

printf "deb https://packages.adoptium.net/artifactory/deb %s main\n" $(lsb_release -cs) \
  | sudo tee /etc/apt/sources.list.d/adoptium.list

sudo apt update -q
sudo apt install -qy --no-install-recommends temurin-${JAVA_VERSION}-jdk
java --version
