#!/bin/bash

ZIGVER=$1
if [[ -z "${ZIGVER}" ]]; then
  ZIGVER=0.15.1
fi


mkdir /usr/local/zig
ARCH=$(uname -m)
curl -sSLf "https://ziglang.org/download/$ZIGVER/zig-$ARCH-linux-$ZIGVER.tar.xz" \
  | tar --strip-components=1  \
        -C /usr/local/zig     \
        -xJf -

ln -s /usr/local/zig/zig /usr/local/bin/zig

echo -n "Installed zig version "
zig version