#!/bin/bash

curl -fsSL https://download.docker.com/linux/debian/gpg > /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc]" \
     "https://download.docker.com/linux/debian"                                      \
     "$(lsb_release -cs)"                                                            \
     "stable"                                                                        \
  > /etc/apt/sources.list.d/docker.list

apt update -q
apt install -y docker-ce-cli
