#!/bin/bash

curl -fsSL https://download.docker.com/linux/debian/gpg \
  | sudo tee /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc]" \
      "https://download.docker.com/linux/debian"                                      \
      "$(lsb_release -cs)"                                                            \
      "stable"                                                                        \
  | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt update -q
sudo apt install -y docker-ce-cli
