#!/bin/bash

POSTGRES_VERSION=$1
if [[ -z "${POSTGRES_VERSION}" ]]; then
  POSTGRES_VERSION=17
fi

mkdir -p /usr/share/postgresql
curl -sSLf https://www.postgresql.org/media/keys/ACCC4CF8.asc \
     -o /usr/share/postgresql/apt.postgresql.org.asc
echo "deb [signed-by=/usr/share/postgresql/apt.postgresql.org.asc]" \
     "https://apt.postgresql.org/pub/repos/apt"                     \
     "$(lsb_release -cs)-pgdg"                                      \
     "main"                                                         \
     > /etc/apt/sources.list.d/pgdg.list

apt update -q
apt install -y postgresql-client-${POSTGRES_VERSION}

psql --version
