#!/bin/bash

RELEASE=$1
if [[ -z "${RELEASE}" ]]; then
  RELEASE=$(curl -sSLf "https://api.github.com/repos/babashka/babashka/releases/latest" | jq -r ".tag_name[1:]")
fi

echo "Installing Babashka ${RELEASE}..."

case $(uname -m) in
  arm64) ARCH=aarch64;;
  *)     ARCH=amd64;;
esac

mkdir -p $HOME/.local/bin

curl -sSLf "https://github.com/babashka/babashka/releases/download/v${RELEASE}/babashka-${RELEASE}-linux-${ARCH}-static.tar.gz" \
  | tar xzCf $HOME/.local/bin -
  
bb --version

