#!/bin/bash

RELEASE=$(curl -sSLf "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | jq -r ".tag_name[1:]")

echo "Installing LazyGit ${RELEASE}..."

case $(uname -m) in
  aarch64) ARCH=arm64;;
  x86_64)  ARCH=x86_64;;
esac

mkdir -p $HOME/.local/bin

curl -sSLf "https://github.com/jesseduffield/lazygit/releases/download/v${RELEASE}/lazygit_${RELEASE}_Linux_${ARCH}.tar.gz" \
  | tar -C $HOME/.local/bin -xzf - lazygit
