#!/bin/bash

# kubectl:

RELEASE=$(curl -sSLf https://dl.k8s.io/release/stable.txt)
ARCH=$(dpkg --print-architecture)

curl -sSLf "https://dl.k8s.io/release/${RELEASE}/bin/linux/${ARCH}/kubectl" > /usr/local/bin/kubectl
chmod 0755 /usr/local/bin/kubectl
