---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name:  app
      image: jarppe/clj-devcontainer:latest
      imagePullPolicy: Always
      args:  ["sleep", "infinity"]
      env:
       - name: NODE_NAME
         valueFrom:
           fieldRef:
             fieldPath: spec.nodeName
       - name: POD_NAME
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
       - name: NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       - name: POD_IP
         valueFrom:
           fieldRef:
             fieldPath: status.podIP
       - name: SERVICE_ACCOUNT
         valueFrom:
           fieldRef:
             fieldPath: spec.serviceAccountName
      volumeMounts:
        - name:      persistent-storage
          subPath:   workspace
          mountPath: /workspace
        - name:      persistent-storage
          subPath:   vscode-cache
          mountPath: /root/.vscode-server
        - name:      ssh-keys
          subPath:   id_ed25519
          mountPath: /root/.ssh/id_ed25519
        - name:      ssh-keys
          subPath:   id_ed25519.pub
          mountPath: /root/.ssh/id_ed25519.pub
        - name: user-env
          subPath:   .envrc
          mountPath: "/root/.envrc"
          readOnly: true
      resources:
        requests:
          cpu:    1000m
          memory: 2000Mi          
        limits:
          cpu:    2000m
          memory: 4000Mi
    - name: kube-proxy
      image: bitnami/kubectl:latest
      imagePullPolicy: IfNotPresent
      command:
        - kubectl
      args:
        - proxy
        - '--port'
        - '9000'
      resources:
        requests:
          cpu:    100m
          memory: 200Mi          
        limits:
          cpu:    200m
          memory: 400Mi
      volumeMounts:
        - name: kube-api-access
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      terminationMessagePath: /dev/termination-log
  serviceAccountName: sa
  serviceAccount: sa
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc
    - name: ssh-keys
      secret:
        secretName: ssh-secrets
        defaultMode: 256
    - name: user-env
      configMap:
        name: user-env
    - name: kube-api-access
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
