name: build-and-push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer.json
          imageName:  jarppe/clj-devcontainer
          imageTag:   latest
          cacheFrom:  jarppe/clj-devcontainer:latest
          platform:   linux/amd64,linux/arm64
          push:       always
