name: build-and-push

on:
  push:
    branches:
      - release

env:
  GHR_TAG: jarppe/clj-devcontainer:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Build ID and date
        run: |
          echo "build_date=$(date --iso-8601=seconds)" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${GHR_TAG}
          runCmd: sleep infinity
          push: always
          platform: linux/amd64,linux/arm64
