name: build-and-push

on:
  push:
    branches:
      - main

env:
  GHR_TAG: jarppe/clj-devcontainer:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer.json
          imageName: jarppe/clj-devcontainer
          imageTag: latest
          cacheFrom: jarppe/clj-devcontainer:latest
          push: always
          platform: linux/amd64,linux/arm64
